require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - bin/bundle
    - repositories/**/*

#
# Exclude migrations and tests directory from certain linters
#
Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb
Style/Documentation:
  Exclude:
    - db/migrate/*.rb
    - test/**/*
