version: '2.2'
services:
  db:
    image: postgres:12.2
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./persistent/postgres/:/var/lib/postgresql/data/pgdata

  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/srv/app:cached
      - /srv/app/persistent
    env_file:
      - .env
    command: tail -f /dev/null
    depends_on:
      - db
